apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/desperatenix/test.git
              revision: HEAD
              files:
                - path: lists/infra.yaml
          - list:
              elementsYaml: "{{ .key.components | toJson }}"
  template:
    metadata:
      name: "{{.name}}"
    spec:
      project: default
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      sources:
        - chart: "{{.chart}}"
          repoURL: "{{.repoUrl}}"
          targetRevision: "{{.version}}"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{.namespace}}"
